# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160627_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
